/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.br.revisandocodigo.treinamento.guestbook.service.base;

import com.br.revisandocodigo.treinamento.guestbook.service.GuestbookEntryLocalService;
import com.br.revisandocodigo.treinamento.guestbook.service.impl.GuestbookEntryServiceImpl;
import com.br.revisandocodigo.treinamento.guestbook.model.GuestbookEntry;
import com.br.revisandocodigo.treinamento.guestbook.service.GuestbookEntryService;
import com.br.revisandocodigo.treinamento.guestbook.service.GuestbookEntryServiceUtil;
import com.br.revisandocodigo.treinamento.guestbook.service.persistence.GuestbookEntryPersistence;
import com.br.revisandocodigo.treinamento.guestbook.service.persistence.GuestbookPersistence;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the guestbook entry remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link GuestbookEntryServiceImpl}.
 * </p>
 *
 * @author wesleyroberts
 * @see GuestbookEntryServiceImpl
 * @generated
 */
public abstract class GuestbookEntryServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, GuestbookEntryService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>GuestbookEntryService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>GuestbookEntryServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		GuestbookEntryServiceUtil.setService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			GuestbookEntryService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		guestbookEntryService = (GuestbookEntryService)aopProxy;

		GuestbookEntryServiceUtil.setService(guestbookEntryService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return GuestbookEntryService.class.getName();
	}

	protected Class<?> getModelClass() {
		return GuestbookEntry.class;
	}

	protected String getModelClassName() {
		return GuestbookEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = guestbookEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected GuestbookPersistence guestbookPersistence;

	@Reference
	protected GuestbookEntryLocalService
		guestbookEntryLocalService;

	protected GuestbookEntryService guestbookEntryService;

	@Reference
	protected GuestbookEntryPersistence guestbookEntryPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		GuestbookEntryServiceBaseImpl.class);

}